
# Thanks to https://digitalis.io/blog/apache-cassandra/containerized-cassandra-cluster-for-local-testing/

# Run Cassandra single node: docker-compose -f <this-filename> up -d

# List containers: docker ps

# Show cluster status: docker exec cassandra-db nodetool status

# Run DML & DQL commands: docker exec -it cassandra-db cqlsh

# Stop cluster: docker-compose -f <this-filename> down

version: '3.9'
networks:
  cassandra:
services:
  cassandra-db:
    image: cassandra:3.11.10
    container_name: cassandra-db
    hostname: cassandra-db
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      - cassandra
    ports:
      - "9042:9042"
    volumes:
      - /tmp/data/cassandra-db:/var/lib/cassandra
    environment: &environment
        CASSANDRA_CLUSTER_NAME: SolarSystem
        CASSANDRA_DC: Mars
        CASSANDRA_RACK: West
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
        CASSANDRA_NUM_TOKENS: 128
